from collections.abc import Iterable, MutableSequence
from typing import TypeVar

_T = TypeVar("_T")
_StreamId = int | str | bytes

class Generator:
    def __init__(self, seed: int = 0) -> None: ...
    @classmethod
    def from_entropy(cls) -> Generator: ...
    @classmethod
    def for_stream(cls, root_seed: int, stream_id: _StreamId) -> Generator: ...
    def seed(self, value: int = 0) -> None: ...
    def reseed_from_entropy(self) -> None: ...
    def percent_true(
        self, percent: float = 50.0, *, count: int | None = None
    ) -> bool | list[bool]: ...
    def bernoulli_variate(
        self, probability: float = 0.5, *, count: int | None = None
    ) -> bool | list[bool]: ...
    def random_below(self, limit: int, *, count: int | None = None) -> int | list[int]: ...
    def random_index(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def random_int(self, low: int, high: int, *, count: int | None = None) -> int | list[int]: ...
    def random_uint(self, low: int, high: int, *, count: int | None = None) -> int | list[int]: ...
    def random_range(
        self, start: int, stop: int | None = None, step: int = 1, *, count: int | None = None
    ) -> int | list[int]: ...
    def d(self, sides: int = 20, *, count: int | None = None) -> int | list[int]: ...
    def dice(
        self, rolls: int = 1, sides: int = 20, *, count: int | None = None
    ) -> int | list[int]: ...
    def ability_dice(self, rolls: int = 4, *, count: int | None = None) -> int | list[int]: ...
    def plus_or_minus(self, radius: int = 1, *, count: int | None = None) -> int | list[int]: ...
    def plus_or_minus_triangular(
        self, radius: int = 1, *, count: int | None = None
    ) -> int | list[int]: ...
    def plus_or_minus_normal(
        self, radius: int = 1, *, count: int | None = None
    ) -> int | list[int]: ...
    def canonical(self, *, count: int | None = None) -> float | list[float]: ...
    def random_float(
        self, low: float = 0.0, high: float = 1.0, *, count: int | None = None
    ) -> float | list[float]: ...
    def triangular(
        self, low: float, high: float, mode: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def beta_variate(
        self, alpha: float, beta: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def pareto_variate(self, alpha: float, *, count: int | None = None) -> float | list[float]: ...
    def vonmises_variate(
        self, mu: float, kappa: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def binomial_variate(
        self, trials: int, probability: float, *, count: int | None = None
    ) -> int | list[int]: ...
    def negative_binomial_variate(
        self, successes: int, probability: float, *, count: int | None = None
    ) -> int | list[int]: ...
    def geometric_variate(
        self, probability: float, *, count: int | None = None
    ) -> int | list[int]: ...
    def poisson_variate(self, mean: float, *, count: int | None = None) -> int | list[int]: ...
    def exponential_variate(
        self, rate: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def gamma_variate(
        self, shape: float, scale: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def weibull_variate(
        self, shape: float, scale: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def normal_variate(
        self, mean: float, std_dev: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def log_normal_variate(
        self, log_mean: float, log_deviation: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def extreme_value_variate(
        self, location: float, scale: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def chi_squared_variate(
        self, degrees_of_freedom: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def cauchy_variate(
        self, location: float, scale: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def fisher_f_variate(
        self, degrees_1: float, degrees_2: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def student_t_variate(
        self, degrees_of_freedom: float, *, count: int | None = None
    ) -> float | list[float]: ...
    def front_triangular(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def center_triangular(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def back_triangular(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def mixed_triangular(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def front_exponential(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def center_normal(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def back_exponential(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def mixed_exponential_normal(
        self, size: int, *, count: int | None = None
    ) -> int | list[int]: ...
    def front_poisson(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def edge_poisson(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def back_poisson(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def quantum_monty(self, size: int, *, count: int | None = None) -> int | list[int]: ...
    def random_value(self, data: Iterable[_T]) -> _T: ...
    def shuffle(self, data: MutableSequence[_T]) -> None: ...
    def sample(self, population: Iterable[_T], k: int) -> list[_T]: ...

def storm_version() -> str: ...
def seed(value: int = 0) -> None: ...
def from_entropy() -> Generator: ...
def for_stream(root_seed: int, stream_id: _StreamId) -> Generator: ...
def shuffle(data: MutableSequence[_T]) -> None: ...
def percent_true(percent: float = 50.0, *, count: int | None = None) -> bool | list[bool]: ...
def bernoulli_variate(
    probability: float = 0.5, *, count: int | None = None
) -> bool | list[bool]: ...
def random_below(limit: int, *, count: int | None = None) -> int | list[int]: ...
def random_index(size: int, *, count: int | None = None) -> int | list[int]: ...
def random_int(low: int, high: int, *, count: int | None = None) -> int | list[int]: ...
def random_uint(low: int, high: int, *, count: int | None = None) -> int | list[int]: ...
def random_range(
    start: int, stop: int | None = None, step: int = 1, *, count: int | None = None
) -> int | list[int]: ...
def d(sides: int = 20, *, count: int | None = None) -> int | list[int]: ...
def dice(rolls: int = 1, sides: int = 20, *, count: int | None = None) -> int | list[int]: ...
def ability_dice(rolls: int = 4, *, count: int | None = None) -> int | list[int]: ...
def plus_or_minus(radius: int = 1, *, count: int | None = None) -> int | list[int]: ...
def plus_or_minus_triangular(radius: int = 1, *, count: int | None = None) -> int | list[int]: ...
def plus_or_minus_normal(radius: int = 1, *, count: int | None = None) -> int | list[int]: ...
def canonical(*, count: int | None = None) -> float | list[float]: ...
def random_float(
    low: float = 0.0, high: float = 1.0, *, count: int | None = None
) -> float | list[float]: ...
def triangular(
    low: float, high: float, mode: float, *, count: int | None = None
) -> float | list[float]: ...
def beta_variate(alpha: float, beta: float, *, count: int | None = None) -> float | list[float]: ...
def pareto_variate(alpha: float, *, count: int | None = None) -> float | list[float]: ...
def vonmises_variate(
    mu: float, kappa: float, *, count: int | None = None
) -> float | list[float]: ...
def binomial_variate(
    trials: int, probability: float, *, count: int | None = None
) -> int | list[int]: ...
def negative_binomial_variate(
    successes: int, probability: float, *, count: int | None = None
) -> int | list[int]: ...
def geometric_variate(probability: float, *, count: int | None = None) -> int | list[int]: ...
def poisson_variate(mean: float, *, count: int | None = None) -> int | list[int]: ...
def exponential_variate(rate: float, *, count: int | None = None) -> float | list[float]: ...
def gamma_variate(
    shape: float, scale: float, *, count: int | None = None
) -> float | list[float]: ...
def weibull_variate(
    shape: float, scale: float, *, count: int | None = None
) -> float | list[float]: ...
def normal_variate(
    mean: float, std_dev: float, *, count: int | None = None
) -> float | list[float]: ...
def log_normal_variate(
    log_mean: float, log_deviation: float, *, count: int | None = None
) -> float | list[float]: ...
def extreme_value_variate(
    location: float, scale: float, *, count: int | None = None
) -> float | list[float]: ...
def chi_squared_variate(
    degrees_of_freedom: float, *, count: int | None = None
) -> float | list[float]: ...
def cauchy_variate(
    location: float, scale: float, *, count: int | None = None
) -> float | list[float]: ...
def fisher_f_variate(
    degrees_1: float, degrees_2: float, *, count: int | None = None
) -> float | list[float]: ...
def student_t_variate(
    degrees_of_freedom: float, *, count: int | None = None
) -> float | list[float]: ...
def front_triangular(size: int, *, count: int | None = None) -> int | list[int]: ...
def center_triangular(size: int, *, count: int | None = None) -> int | list[int]: ...
def back_triangular(size: int, *, count: int | None = None) -> int | list[int]: ...
def mixed_triangular(size: int, *, count: int | None = None) -> int | list[int]: ...
def front_exponential(size: int, *, count: int | None = None) -> int | list[int]: ...
def center_normal(size: int, *, count: int | None = None) -> int | list[int]: ...
def back_exponential(size: int, *, count: int | None = None) -> int | list[int]: ...
def mixed_exponential_normal(size: int, *, count: int | None = None) -> int | list[int]: ...
def front_poisson(size: int, *, count: int | None = None) -> int | list[int]: ...
def edge_poisson(size: int, *, count: int | None = None) -> int | list[int]: ...
def back_poisson(size: int, *, count: int | None = None) -> int | list[int]: ...
def quantum_monty(size: int, *, count: int | None = None) -> int | list[int]: ...
