from collections.abc import Callable, Iterable, MutableSequence
from typing import Self, TypeVar, overload

_T = TypeVar("_T")
_StreamId = int | str | bytes

class Generator:
    @overload
    def percent_true(self, percent: float = 50.0, *, count: None = None) -> bool: ...
    @overload
    def percent_true(self, percent: float = 50.0, *, count: int) -> list[bool]: ...
    @overload
    def percent_true(self, percent: float = 50.0, *, count: int | None) -> bool | list[bool]: ...
    @overload
    def bernoulli_variate(self, probability: float = 0.5, *, count: None = None) -> bool: ...
    @overload
    def bernoulli_variate(self, probability: float = 0.5, *, count: int) -> list[bool]: ...
    @overload
    def bernoulli_variate(
        self, probability: float = 0.5, *, count: int | None
    ) -> bool | list[bool]: ...
    @overload
    def random_below(self, limit: int, *, count: None = None) -> int: ...
    @overload
    def random_below(self, limit: int, *, count: int) -> list[int]: ...
    @overload
    def random_below(self, limit: int, *, count: int | None) -> int | list[int]: ...
    @overload
    def random_index(self, size: int, *, count: None = None) -> int: ...
    @overload
    def random_index(self, size: int, *, count: int) -> list[int]: ...
    @overload
    def random_index(self, size: int, *, count: int | None) -> int | list[int]: ...
    @overload
    def random_int(self, low: int, high: int, *, count: None = None) -> int: ...
    @overload
    def random_int(self, low: int, high: int, *, count: int) -> list[int]: ...
    @overload
    def random_int(self, low: int, high: int, *, count: int | None) -> int | list[int]: ...
    @overload
    def random_range(
        self, start: int, stop: int | None = None, step: int = 1, *, count: None = None
    ) -> int: ...
    @overload
    def random_range(
        self, start: int, stop: int | None = None, step: int = 1, *, count: int
    ) -> list[int]: ...
    @overload
    def random_range(
        self, start: int, stop: int | None = None, step: int = 1, *, count: int | None
    ) -> int | list[int]: ...
    @overload
    def d(self, sides: int = 20, *, count: None = None) -> int: ...
    @overload
    def d(self, sides: int = 20, *, count: int) -> list[int]: ...
    @overload
    def d(self, sides: int = 20, *, count: int | None) -> int | list[int]: ...
    @overload
    def dice(self, rolls: int = 1, sides: int = 20, *, count: None = None) -> int: ...
    @overload
    def dice(self, rolls: int = 1, sides: int = 20, *, count: int) -> list[int]: ...
    @overload
    def dice(self, rolls: int = 1, sides: int = 20, *, count: int | None) -> int | list[int]: ...
    @overload
    def ability_dice(self, rolls: int = 4, *, count: None = None) -> int: ...
    @overload
    def ability_dice(self, rolls: int = 4, *, count: int) -> list[int]: ...
    @overload
    def ability_dice(self, rolls: int = 4, *, count: int | None) -> int | list[int]: ...
    @overload
    def plus_or_minus(self, radius: int = 1, *, count: None = None) -> int: ...
    @overload
    def plus_or_minus(self, radius: int = 1, *, count: int) -> list[int]: ...
    @overload
    def plus_or_minus(self, radius: int = 1, *, count: int | None) -> int | list[int]: ...
    @overload
    def plus_or_minus_triangular(self, radius: int = 1, *, count: None = None) -> int: ...
    @overload
    def plus_or_minus_triangular(self, radius: int = 1, *, count: int) -> list[int]: ...
    @overload
    def plus_or_minus_triangular(
        self, radius: int = 1, *, count: int | None
    ) -> int | list[int]: ...
    @overload
    def plus_or_minus_normal(self, radius: int = 1, *, count: None = None) -> int: ...
    @overload
    def plus_or_minus_normal(self, radius: int = 1, *, count: int) -> list[int]: ...
    @overload
    def plus_or_minus_normal(self, radius: int = 1, *, count: int | None) -> int | list[int]: ...
    @overload
    def canonical(self, *, count: None = None) -> float: ...
    @overload
    def canonical(self, *, count: int) -> list[float]: ...
    @overload
    def canonical(self, *, count: int | None) -> float | list[float]: ...
    @overload
    def random_float(self, low: float = 0.0, high: float = 1.0, *, count: None = None) -> float: ...
    @overload
    def random_float(self, low: float = 0.0, high: float = 1.0, *, count: int) -> list[float]: ...
    @overload
    def random_float(
        self, low: float = 0.0, high: float = 1.0, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def triangular(self, low: float, high: float, mode: float, *, count: None = None) -> float: ...
    @overload
    def triangular(self, low: float, high: float, mode: float, *, count: int) -> list[float]: ...
    @overload
    def triangular(
        self, low: float, high: float, mode: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def beta_variate(self, alpha: float, beta: float, *, count: None = None) -> float: ...
    @overload
    def beta_variate(self, alpha: float, beta: float, *, count: int) -> list[float]: ...
    @overload
    def beta_variate(
        self, alpha: float, beta: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def pareto_variate(self, alpha: float, *, count: None = None) -> float: ...
    @overload
    def pareto_variate(self, alpha: float, *, count: int) -> list[float]: ...
    @overload
    def pareto_variate(self, alpha: float, *, count: int | None) -> float | list[float]: ...
    @overload
    def vonmises_variate(self, mu: float, kappa: float, *, count: None = None) -> float: ...
    @overload
    def vonmises_variate(self, mu: float, kappa: float, *, count: int) -> list[float]: ...
    @overload
    def vonmises_variate(
        self, mu: float, kappa: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def binomial_variate(self, trials: int, probability: float, *, count: None = None) -> int: ...
    @overload
    def binomial_variate(self, trials: int, probability: float, *, count: int) -> list[int]: ...
    @overload
    def binomial_variate(
        self, trials: int, probability: float, *, count: int | None
    ) -> int | list[int]: ...
    @overload
    def negative_binomial_variate(
        self, successes: int, probability: float, *, count: None = None
    ) -> int: ...
    @overload
    def negative_binomial_variate(
        self, successes: int, probability: float, *, count: int
    ) -> list[int]: ...
    @overload
    def negative_binomial_variate(
        self, successes: int, probability: float, *, count: int | None
    ) -> int | list[int]: ...
    @overload
    def geometric_variate(self, probability: float, *, count: None = None) -> int: ...
    @overload
    def geometric_variate(self, probability: float, *, count: int) -> list[int]: ...
    @overload
    def geometric_variate(self, probability: float, *, count: int | None) -> int | list[int]: ...
    @overload
    def poisson_variate(self, mean: float, *, count: None = None) -> int: ...
    @overload
    def poisson_variate(self, mean: float, *, count: int) -> list[int]: ...
    @overload
    def poisson_variate(self, mean: float, *, count: int | None) -> int | list[int]: ...
    @overload
    def exponential_variate(self, rate: float, *, count: None = None) -> float: ...
    @overload
    def exponential_variate(self, rate: float, *, count: int) -> list[float]: ...
    @overload
    def exponential_variate(self, rate: float, *, count: int | None) -> float | list[float]: ...
    @overload
    def gamma_variate(self, shape: float, scale: float, *, count: None = None) -> float: ...
    @overload
    def gamma_variate(self, shape: float, scale: float, *, count: int) -> list[float]: ...
    @overload
    def gamma_variate(
        self, shape: float, scale: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def weibull_variate(self, shape: float, scale: float, *, count: None = None) -> float: ...
    @overload
    def weibull_variate(self, shape: float, scale: float, *, count: int) -> list[float]: ...
    @overload
    def weibull_variate(
        self, shape: float, scale: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def normal_variate(self, mean: float, std_dev: float, *, count: None = None) -> float: ...
    @overload
    def normal_variate(self, mean: float, std_dev: float, *, count: int) -> list[float]: ...
    @overload
    def normal_variate(
        self, mean: float, std_dev: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def log_normal_variate(
        self, log_mean: float, log_deviation: float, *, count: None = None
    ) -> float: ...
    @overload
    def log_normal_variate(
        self, log_mean: float, log_deviation: float, *, count: int
    ) -> list[float]: ...
    @overload
    def log_normal_variate(
        self, log_mean: float, log_deviation: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def extreme_value_variate(
        self, location: float, scale: float, *, count: None = None
    ) -> float: ...
    @overload
    def extreme_value_variate(
        self, location: float, scale: float, *, count: int
    ) -> list[float]: ...
    @overload
    def extreme_value_variate(
        self, location: float, scale: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def chi_squared_variate(self, degrees_of_freedom: float, *, count: None = None) -> float: ...
    @overload
    def chi_squared_variate(self, degrees_of_freedom: float, *, count: int) -> list[float]: ...
    @overload
    def chi_squared_variate(
        self, degrees_of_freedom: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def cauchy_variate(self, location: float, scale: float, *, count: None = None) -> float: ...
    @overload
    def cauchy_variate(self, location: float, scale: float, *, count: int) -> list[float]: ...
    @overload
    def cauchy_variate(
        self, location: float, scale: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def fisher_f_variate(
        self, degrees_1: float, degrees_2: float, *, count: None = None
    ) -> float: ...
    @overload
    def fisher_f_variate(
        self, degrees_1: float, degrees_2: float, *, count: int
    ) -> list[float]: ...
    @overload
    def fisher_f_variate(
        self, degrees_1: float, degrees_2: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def student_t_variate(self, degrees_of_freedom: float, *, count: None = None) -> float: ...
    @overload
    def student_t_variate(self, degrees_of_freedom: float, *, count: int) -> list[float]: ...
    @overload
    def student_t_variate(
        self, degrees_of_freedom: float, *, count: int | None
    ) -> float | list[float]: ...
    @overload
    def front_triangular(self, size: int, *, count: None = None) -> int: ...
    @overload
    def front_triangular(self, size: int, *, count: int) -> list[int]: ...
    @overload
    def front_triangular(self, size: int, *, count: int | None) -> int | list[int]: ...
    @overload
    def center_triangular(self, size: int, *, count: None = None) -> int: ...
    @overload
    def center_triangular(self, size: int, *, count: int) -> list[int]: ...
    @overload
    def center_triangular(self, size: int, *, count: int | None) -> int | list[int]: ...
    @overload
    def back_triangular(self, size: int, *, count: None = None) -> int: ...
    @overload
    def back_triangular(self, size: int, *, count: int) -> list[int]: ...
    @overload
    def back_triangular(self, size: int, *, count: int | None) -> int | list[int]: ...
    def _front_poisson(self, size: int) -> int: ...
    def __init__(self, seed: int = 0) -> None: ...
    @classmethod
    def from_entropy(cls) -> Self: ...
    @classmethod
    def for_stream(cls, root_seed: int, stream_id: _StreamId) -> Self: ...
    def seed(self, value: int = 0) -> None: ...
    def reseed_from_entropy(self) -> None: ...
    def random_value(self, data: Iterable[_T]) -> _T: ...
    def shuffle(self, data: MutableSequence[_T]) -> None: ...
    def sample(self, population: Iterable[_T], k: int) -> list[_T]: ...
    def _sample_materialized(self, working: list[_T], checked_k: int) -> list[_T]: ...

def storm_version() -> str: ...
def seed(value: int = 0) -> None: ...
def from_entropy() -> Generator: ...
def for_stream(root_seed: int, stream_id: _StreamId) -> Generator: ...
def shuffle(data: MutableSequence[_T]) -> None: ...
def _benchmark_shuffle_knuth_b(data: MutableSequence[_T]) -> None: ...
def _benchmark_shuffle_fisher_yates(data: MutableSequence[_T]) -> None: ...
def _sample_materialized(working: list[_T], checked_k: int) -> list[_T]: ...
def _random_value_materialized(data: tuple[_T, ...] | list[_T]) -> _T: ...
def _wide_index_selector(size: int, generator: Generator | None = None) -> Callable[[], int]: ...
def _prepared_weighted_index(
    weights: Iterable[float], generator: Generator | None = None
) -> Callable[[], int]: ...
@overload
def percent_true(percent: float = 50.0, *, count: None = None) -> bool: ...
@overload
def percent_true(percent: float = 50.0, *, count: int) -> list[bool]: ...
@overload
def percent_true(percent: float = 50.0, *, count: int | None) -> bool | list[bool]: ...
@overload
def bernoulli_variate(probability: float = 0.5, *, count: None = None) -> bool: ...
@overload
def bernoulli_variate(probability: float = 0.5, *, count: int) -> list[bool]: ...
@overload
def bernoulli_variate(probability: float = 0.5, *, count: int | None) -> bool | list[bool]: ...
@overload
def random_below(limit: int, *, count: None = None) -> int: ...
@overload
def random_below(limit: int, *, count: int) -> list[int]: ...
@overload
def random_below(limit: int, *, count: int | None) -> int | list[int]: ...
@overload
def random_index(size: int, *, count: None = None) -> int: ...
@overload
def random_index(size: int, *, count: int) -> list[int]: ...
@overload
def random_index(size: int, *, count: int | None) -> int | list[int]: ...
@overload
def random_int(low: int, high: int, *, count: None = None) -> int: ...
@overload
def random_int(low: int, high: int, *, count: int) -> list[int]: ...
@overload
def random_int(low: int, high: int, *, count: int | None) -> int | list[int]: ...
@overload
def random_range(
    start: int, stop: int | None = None, step: int = 1, *, count: None = None
) -> int: ...
@overload
def random_range(
    start: int, stop: int | None = None, step: int = 1, *, count: int
) -> list[int]: ...
@overload
def random_range(
    start: int, stop: int | None = None, step: int = 1, *, count: int | None
) -> int | list[int]: ...
@overload
def d(sides: int = 20, *, count: None = None) -> int: ...
@overload
def d(sides: int = 20, *, count: int) -> list[int]: ...
@overload
def d(sides: int = 20, *, count: int | None) -> int | list[int]: ...
@overload
def dice(rolls: int = 1, sides: int = 20, *, count: None = None) -> int: ...
@overload
def dice(rolls: int = 1, sides: int = 20, *, count: int) -> list[int]: ...
@overload
def dice(rolls: int = 1, sides: int = 20, *, count: int | None) -> int | list[int]: ...
@overload
def ability_dice(rolls: int = 4, *, count: None = None) -> int: ...
@overload
def ability_dice(rolls: int = 4, *, count: int) -> list[int]: ...
@overload
def ability_dice(rolls: int = 4, *, count: int | None) -> int | list[int]: ...
@overload
def plus_or_minus(radius: int = 1, *, count: None = None) -> int: ...
@overload
def plus_or_minus(radius: int = 1, *, count: int) -> list[int]: ...
@overload
def plus_or_minus(radius: int = 1, *, count: int | None) -> int | list[int]: ...
@overload
def plus_or_minus_triangular(radius: int = 1, *, count: None = None) -> int: ...
@overload
def plus_or_minus_triangular(radius: int = 1, *, count: int) -> list[int]: ...
@overload
def plus_or_minus_triangular(radius: int = 1, *, count: int | None) -> int | list[int]: ...
@overload
def plus_or_minus_normal(radius: int = 1, *, count: None = None) -> int: ...
@overload
def plus_or_minus_normal(radius: int = 1, *, count: int) -> list[int]: ...
@overload
def plus_or_minus_normal(radius: int = 1, *, count: int | None) -> int | list[int]: ...
@overload
def canonical(*, count: None = None) -> float: ...
@overload
def canonical(*, count: int) -> list[float]: ...
@overload
def canonical(*, count: int | None) -> float | list[float]: ...
@overload
def random_float(low: float = 0.0, high: float = 1.0, *, count: None = None) -> float: ...
@overload
def random_float(low: float = 0.0, high: float = 1.0, *, count: int) -> list[float]: ...
@overload
def random_float(
    low: float = 0.0, high: float = 1.0, *, count: int | None
) -> float | list[float]: ...
@overload
def triangular(low: float, high: float, mode: float, *, count: None = None) -> float: ...
@overload
def triangular(low: float, high: float, mode: float, *, count: int) -> list[float]: ...
@overload
def triangular(
    low: float, high: float, mode: float, *, count: int | None
) -> float | list[float]: ...
@overload
def beta_variate(alpha: float, beta: float, *, count: None = None) -> float: ...
@overload
def beta_variate(alpha: float, beta: float, *, count: int) -> list[float]: ...
@overload
def beta_variate(alpha: float, beta: float, *, count: int | None) -> float | list[float]: ...
@overload
def pareto_variate(alpha: float, *, count: None = None) -> float: ...
@overload
def pareto_variate(alpha: float, *, count: int) -> list[float]: ...
@overload
def pareto_variate(alpha: float, *, count: int | None) -> float | list[float]: ...
@overload
def vonmises_variate(mu: float, kappa: float, *, count: None = None) -> float: ...
@overload
def vonmises_variate(mu: float, kappa: float, *, count: int) -> list[float]: ...
@overload
def vonmises_variate(mu: float, kappa: float, *, count: int | None) -> float | list[float]: ...
@overload
def binomial_variate(trials: int, probability: float, *, count: None = None) -> int: ...
@overload
def binomial_variate(trials: int, probability: float, *, count: int) -> list[int]: ...
@overload
def binomial_variate(trials: int, probability: float, *, count: int | None) -> int | list[int]: ...
@overload
def negative_binomial_variate(successes: int, probability: float, *, count: None = None) -> int: ...
@overload
def negative_binomial_variate(successes: int, probability: float, *, count: int) -> list[int]: ...
@overload
def negative_binomial_variate(
    successes: int, probability: float, *, count: int | None
) -> int | list[int]: ...
@overload
def geometric_variate(probability: float, *, count: None = None) -> int: ...
@overload
def geometric_variate(probability: float, *, count: int) -> list[int]: ...
@overload
def geometric_variate(probability: float, *, count: int | None) -> int | list[int]: ...
@overload
def poisson_variate(mean: float, *, count: None = None) -> int: ...
@overload
def poisson_variate(mean: float, *, count: int) -> list[int]: ...
@overload
def poisson_variate(mean: float, *, count: int | None) -> int | list[int]: ...
@overload
def exponential_variate(rate: float, *, count: None = None) -> float: ...
@overload
def exponential_variate(rate: float, *, count: int) -> list[float]: ...
@overload
def exponential_variate(rate: float, *, count: int | None) -> float | list[float]: ...
@overload
def gamma_variate(shape: float, scale: float, *, count: None = None) -> float: ...
@overload
def gamma_variate(shape: float, scale: float, *, count: int) -> list[float]: ...
@overload
def gamma_variate(shape: float, scale: float, *, count: int | None) -> float | list[float]: ...
@overload
def weibull_variate(shape: float, scale: float, *, count: None = None) -> float: ...
@overload
def weibull_variate(shape: float, scale: float, *, count: int) -> list[float]: ...
@overload
def weibull_variate(shape: float, scale: float, *, count: int | None) -> float | list[float]: ...
@overload
def normal_variate(mean: float, std_dev: float, *, count: None = None) -> float: ...
@overload
def normal_variate(mean: float, std_dev: float, *, count: int) -> list[float]: ...
@overload
def normal_variate(mean: float, std_dev: float, *, count: int | None) -> float | list[float]: ...
@overload
def log_normal_variate(log_mean: float, log_deviation: float, *, count: None = None) -> float: ...
@overload
def log_normal_variate(log_mean: float, log_deviation: float, *, count: int) -> list[float]: ...
@overload
def log_normal_variate(
    log_mean: float, log_deviation: float, *, count: int | None
) -> float | list[float]: ...
@overload
def extreme_value_variate(location: float, scale: float, *, count: None = None) -> float: ...
@overload
def extreme_value_variate(location: float, scale: float, *, count: int) -> list[float]: ...
@overload
def extreme_value_variate(
    location: float, scale: float, *, count: int | None
) -> float | list[float]: ...
@overload
def chi_squared_variate(degrees_of_freedom: float, *, count: None = None) -> float: ...
@overload
def chi_squared_variate(degrees_of_freedom: float, *, count: int) -> list[float]: ...
@overload
def chi_squared_variate(degrees_of_freedom: float, *, count: int | None) -> float | list[float]: ...
@overload
def cauchy_variate(location: float, scale: float, *, count: None = None) -> float: ...
@overload
def cauchy_variate(location: float, scale: float, *, count: int) -> list[float]: ...
@overload
def cauchy_variate(location: float, scale: float, *, count: int | None) -> float | list[float]: ...
@overload
def fisher_f_variate(degrees_1: float, degrees_2: float, *, count: None = None) -> float: ...
@overload
def fisher_f_variate(degrees_1: float, degrees_2: float, *, count: int) -> list[float]: ...
@overload
def fisher_f_variate(
    degrees_1: float, degrees_2: float, *, count: int | None
) -> float | list[float]: ...
@overload
def student_t_variate(degrees_of_freedom: float, *, count: None = None) -> float: ...
@overload
def student_t_variate(degrees_of_freedom: float, *, count: int) -> list[float]: ...
@overload
def student_t_variate(degrees_of_freedom: float, *, count: int | None) -> float | list[float]: ...
@overload
def front_triangular(size: int, *, count: None = None) -> int: ...
@overload
def front_triangular(size: int, *, count: int) -> list[int]: ...
@overload
def front_triangular(size: int, *, count: int | None) -> int | list[int]: ...
@overload
def center_triangular(size: int, *, count: None = None) -> int: ...
@overload
def center_triangular(size: int, *, count: int) -> list[int]: ...
@overload
def center_triangular(size: int, *, count: int | None) -> int | list[int]: ...
@overload
def back_triangular(size: int, *, count: None = None) -> int: ...
@overload
def back_triangular(size: int, *, count: int) -> list[int]: ...
@overload
def back_triangular(size: int, *, count: int | None) -> int | list[int]: ...
def _front_poisson(size: int) -> int: ...
